[package]
name = "basic_platformer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version="0.13.2" , features=["dynamic_linking"]}
serde_json = "1.0"

[profile.dev]
opt-level=1

[profile.dev.package."*"]
opt-level=3